# Generated by Django 4.0.3 on 2022-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='auther',
            new_name='author',
        ),
    ]
